Name : SILVA G.B.N.M. <br>
Index No: 190592X

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
from scipy.linalg import null_space

Q1

In [9]:
f = open(r'images/templeSparseRing/templeSR_par.txt','r')
assert f is not None
n = int(f.readline())

#First Image
l = f.readline().split()
im1_fn = l[0]
k1 = np.array([float(i) for i in l[1:10]]).reshape((3,3))
r1 = np.array([float(i) for i in l[10:19]]).reshape((3,3))
t1 = np.array([float(i) for i in l[19:22]]).reshape((3,1))

#Second Image
l = f.readline().split()
im2_fn = l[0]
k2 = np.array([float(i) for i in l[1:10]]).reshape((3,3))
r2 = np.array([float(i) for i in l[10:19]]).reshape((3,3))
t2 = np.array([float(i) for i in l[19:22]]).reshape((3,1))

Q2

In [11]:
P1 = k1 @ np.hstack((r1,t1))
P2 = k2 @ np.hstack((r2,t2))

print("P1 = ",P1)
print("P2 = ",P2)

P1 =  [[ 4.80251845e+01  1.44011271e+03 -5.71648932e+02  7.53293366e+01]
 [ 1.53577034e+03 -6.41434324e+01 -1.63127843e+02  1.85810055e+02]
 [ 4.88387837e-02 -1.81568392e-01 -9.82164799e-01  6.14604846e-01]]
P2 =  [[-1.55882371e+02  1.44377186e+03 -5.42436214e+02  6.81806220e+01]
 [ 1.34928131e+03 -8.41979541e+01 -7.49443961e+02  1.99929996e+02]
 [-3.40999743e-01 -1.74474039e-01 -9.23730472e-01  6.00850565e-01]]


Q3